[theme]
name = "plain"

[theme.overrides]
separator = ""
info_fg = "#cccccc"
idle_fg = "#cccccc"
warning_fg = "#fbc42d"
good_fg = "#00cd00"
#good_fg="#a4e22e"

[icons]
name = "awesome6"

# [icons.overrides]
#disk_drive="\uf0a0"

[[block]]
block = "focused_window"
# show_marks = "visible"
format = "  {title:66}  "
max_width = 70

[block.theme_overrides]
info_fg = "#fcd088"
idle_fg = "#fcd088"
# good_fg="#00e5e5"

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "*-acpi-*"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used}"

[[block]]
block = "disk_space"
format = " {icon} {available}"
path = "/"
info_type = "available"
unit = "GB"
interval = 10
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
command = '/home/d0np0br3/Scripts/hddtemp.sh'
json = true

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {speed_down;K*b} {speed_up;K*b}"
interval = 3

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[block.theme_overrides]
info_fg = "#00e5e5"
idle_fg = "#00e5e5"
# good_fg="#00e5e5"
